// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModisAPI.Models;

namespace ModisAPI.Migrations
{
    [DbContext(typeof(ModisContext))]
    partial class ModisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ModisAPI.Models.Corso", b =>
                {
                    b.Property<int>("CorsoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DataInOre");

                    b.Property<DateTime>("DataInizio");

                    b.Property<int>("Livello");

                    b.Property<string>("Nome");

                    b.Property<int>("NumeroMassimoPartecipanti");

                    b.HasKey("CorsoId");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("ModisAPI.Models.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cognome");

                    b.Property<string>("Indirizzo");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("ModisAPI.Models.StudenteCorso", b =>
                {
                    b.Property<int>("StudenteId");

                    b.Property<int>("CorsoId");

                    b.HasKey("StudenteId", "CorsoId");

                    b.HasIndex("CorsoId");

                    b.ToTable("StudenteCorsi");
                });

            modelBuilder.Entity("ModisAPI.Models.StudenteCorso", b =>
                {
                    b.HasOne("ModisAPI.Models.Corso", "Corso")
                        .WithMany("StudenteCorsi")
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ModisAPI.Models.Studente", "Studente")
                        .WithMany("StudenteCorsi")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
